# Generated by Django 3.1.1 on 2021-01-15 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='UserInfor',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('username', models.CharField(max_length=64)),
        #         ('gender', models.CharField(choices=[('A', 'Male'), ('B', 'Female')], max_length=64)),
        #         ('email', models.CharField(max_length=64)),
        #         ('birthday', models.DateTimeField()),
        #         ('country', models.CharField(max_length=64)),
        #         ('ID', models.CharField(max_length=64)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leave_city', models.CharField(max_length=100, null=True)),
                ('arrive_city', models.CharField(max_length=100, null=True)),
                ('leave_airport', models.CharField(max_length=100, null=True)),
                ('arrive_airport', models.CharField(max_length=100, null=True)),
                ('leave_time', models.DateTimeField(null=True)),
                ('arrive_time', models.DateTimeField(null=True)),
                ('capacity', models.IntegerField(default=0, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('book_sum', models.IntegerField(default=0, null=True)),
                ('income', models.FloatField(default=0, null=True)),
                ('user', models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
