# Generated by Django 3.1.1 on 2021-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('A', 'Male'), ('B', 'Female')], max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('birthday', models.DateTimeField()),
                ('country', models.CharField(max_length=64)),

            ],
        ),
    ]
